In [1]:
import numpy as np

In [2]:
len_test = 4

for j in reversed(range(len_test)):
    print(j, j+1)

3 4
2 3
1 2
0 1


In [7]:
a = np.array([1, 2, 3, 4])
a = np.reshape(a, (4, 1))
print(a.shape)
c = np.zeros_like(a)

c[0:-1] = a[0:-1] - a[1:]
print()
print(a)
print()
print(c)

c[-1] = a[-1] - 0
print()
print(c)


(4, 1)

[[1]
 [2]
 [3]
 [4]]

[[-1]
 [-1]
 [-1]
 [ 0]]

[[-1]
 [-1]
 [-1]
 [ 4]]


In [8]:
a = np.array([1, 2, 3, 4])
a = np.reshape(a, (4, 1))

b = np.flip(a)

print(a)
print()
print(b)

[[1]
 [2]
 [3]
 [4]]

[[4]
 [3]
 [2]
 [1]]


In [9]:
a = np.array([1, 2, 3])
print(a.shape[0])
print(a)
print()

a = np.insert(a, 2, 8)
print(a.shape)
print(a)

3
[1 2 3]

(4,)
[1 2 8 3]


In [16]:
a = np.array([[10, 20], [30, 40]])
idx = np.array([1, 0])
id_row = np.arange(len(a))

print(id_row)
print(a.shape)
print(a[id_row, idx])

[0 1]
(2, 2)
[20 30]


In [3]:
a = np.array([10, 20])
idx  = 1
#idx = np.array([1, 0])
#id_row = np.arange(len(a))

#print(id_row)
print(a.shape)
print(a[idx])

(2,)
20


In [8]:
name = type(1)
print(name)
if name == type(1):
    print("I'm Int")

<class 'int'>
I'm Int
